### PR TITLE
Added Search

### PR DESCRIPTION
**Pull request by pantharshit00**
This PR added the search functionality required.

HOPE YOU LIKE THIS 
```
            HARSHIT
```

### CODE REVIEW

**Comment by SebastianCApostolescu** [comment]
Doesn't CRA comes with loadash already installed?

**Comment by pantharshit00** [comment]
Doesn't Really if even it come. It is the same thing to bundle debounce from lodash or lodash.debounce. We will not ship whole lodash anyways.

Or if you really want to refactor this do that later.

**Comment by SebastianCApostolescu** [comment]
Got it!

Nice terminal 👍 . What OS are you on?

**Comment by pantharshit00** [comment]
In am on Ubuntu 16.04 LTS

I am using [hyper](hyper.is) as my terminal
Zsh as the shell
agnoster theme for oh my zsh
firacode font

you can get this on bash on windows or mac too!

**Comment by SebastianCApostolescu** [comment]
I really want to use Ubuntu for developing, but after a while it gets slow and sometimes even freezes... And only running 2 terminals (one with server), a few Chrome tabs and Code editor. With the same things or more on Windows, no issues.

**Comment by pantharshit00** [comment]
It has got better after linux 4.10 i have same issues in linux 4.8

**Comment by JesseRWeigel** [comment]
Thanks @pantharshit00 !

**Pull request merged**
