### PR TITLE
Fixed UI glitch

### PR DESCRIPTION
**Pull request by SebastianCApostolescu**
This fixed Issue #45.

Minor `css` was needed.

Bonus: Check the scroll bar in Chrome! 😄

### CODE REVIEW

**Comment by pantharshit00** [comment]
This is awesome @SebastianCApostolescu. Have any ideas about #16. I am having a tough time implementing it since we are using material ui

**Comment by SebastianCApostolescu** [comment]
I'll be looking into it @pantharshit00 !

**Comment by pantharshit00** [comment]
@SebastianCApostolescu I fixed #16 it.See the PR

**Comment by JesseRWeigel** [comment]
Thanks @SebastianCApostolescu !

**Comment by JesseRWeigel** [comment]
This worked well with non-Mac computers. After testing on a Mac I decided to revert. There was a gap on the right side of the screen:
image

If there is some way to use these styles only on non-Mac computers, that would be best.

**Comment by SebastianCApostolescu** [comment]
Hmm.. Can you try again but removing the scroll bar styling? Maybe that was the issue.

**Comment by pantharshit00** [comment]
Maybe we should use browserstack to determice the f*** issue coz i am now pissed with this glitch

**Pull request merged**
