### PR TITLE
Show category name in post preview

### PR DESCRIPTION
**Pull request by SebastianCApostolescu**
Pretty straightforward.
Added an attachment button. This will need further implementation since I don't really know how it should look.
Also, I moved the post image under the title and date, don't really know if it's good or not. Check it out.

PD: It also includes the npm start fix for Windows, which by the time I'm writing this I think you already merged a previous PR.

Side Note: Just notices that GMail has GitHub link support https://i.imgur.com/rWi7URt.png

### CODE REVIEW

**Comment by JesseRWeigel** [comment]
Great job @SebastianCApostolescu ! 
Here is how the attachments are currently displayed:
image

Also, I think the title, date and category should be below the image like this:
image

If you have time to adjust this PR, that would be awesome, otherwise I can make the changes to this branch and merge afterward. Just let me know.

**Comment by SebastianCApostolescu** [comment]
Moved back the image were it was.
For the attachment maybe it's better to show me in the stream how you want it.

**Comment by SebastianCApostolescu** [comment]
Update...
Something similar?

test

**Comment by SebastianCApostolescu** [comment]
Added text (which needs to be truncated #32  ) to the Post Preview.
Check previous photo to see how it looks.

**Comment by JesseRWeigel** [comment]
Thank you @SebastianCApostolescu ! You are awesome!

**Pull request merged**
