### PR TITLE
Filled Space in Grid and fixed error handler

### LINKED ISSUE #16: Remove gaps from grid layout
Maybe try using the masonry react module that was used in the first version of the Resources page for the ci-react project. See this commit ( https://github.com/fus-marcom/ci-react/commit/3edd50549242397e0268cc1c862edff011b8c590#diff-eb5ff544cae584eda8b7362ae88cff46 )

image

### PR DESCRIPTION
**Pull request by pantharshit00**
(Closes #16 )

Hey @JesseRWeigel 
In this PR I have fixed the gaps in the grid. It was a quick an easy fix. Just specified the height to 100%.
I have also fixed the error handler as we changed our renderer to  GridRenderer component. 

HOPE THIS HELPS YOU 
```
          HARSHIT
```

### CODE REVIEW

**Comment by JesseRWeigel** [comment]
I think we need a solution that allows for different card heights. Otherwise we will end up with too much white space in cards with less content, like this:
image

I think something like to potential solution mentioned in #16 will work.

I will leave the PR open in case you want to edit it.

**Comment by pantharshit00** [comment]
OK no probs. But I tried masonry. It is hard to implement in material UI

**Comment by pantharshit00** [comment]
Closing this as to work on masonry

**Comment by pantharshit00** [comment]
#47 now fix this problem

**Pull request closed without merging**
